### ISSUE TITLE
None of the tags you have selected is a blog tag. Please select at least one.

### ISSUE THREAD

**Issue by haexperts2020** [v17development/flarum-blog#106]
Fresh install of latest Flarum and Flarum-Blog. I have tags enabled. 

Try to create first blog post and get this error. 

I am not seeing anywhere in the backend to create a tag as a "Blog Tag"

Any ideas?

**Comment by hrvoje-hr** [comment]
Hi @haexperts2020, it's probably too late for you. You can't create a blog tag, you can select Flarum tags as Blog tags

https://imgur.com/JKksuwS

Also, we can close this issue, as this is not really an issue :)
