### ISSUE TITLE
Revert change that blocks the URL field when fof-upload is enabled

### ISSUE THREAD

**Issue by iamdarkle** [v17development/flarum-blog#120]
As I [mentioned](https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/394) in the Blog discussion on Discuss, it would be nice if the URL field was not blocked when `fof-upload` is enabled, as this makes it impossible to use external URLs if you want to do so in some cases.

**Comment by hasanmerkit** [comment]
This issue still alive.

**Comment by iamdarkle** [comment]
I haven't experienced this problem since it was fixed, what version of the blog are you on?

**Comment by hasanmerkit** [comment]
> I haven't experienced this problem since it was fixed, what version of the blog are you on?

Here is my "php flarum info" output:

`Flarum core 1.4.1
PHP version: 8.1.9
MySQL version: 5.7.38-cll-lve
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, json, iconv, SPL, pcntl, readline, Reflection, session, standard, mbstring, shmop, SimpleXML, tokenizer, xml, bcmath, dom, fileinfo, gd, gmp, imagick, imap, inotify, intl, exif, mcrypt, mysqli, mysqlnd, PDO, pdo_mysql, pdo_sqlite, Phar, posix, soap, xmlreader, xmlwriter, Zend OPcache
+------------------------------------+---------+--------+
| Flarum Extensions                  |         |        |
+------------------------------------+---------+--------+
| ID                                 | Version | Commit |
+------------------------------------+---------+--------+
| flarum-markdown                    | v1.4.0  |        |
| flarum-tags                        | v1.4.0  |        |
| flarum-flags                       | v1.4.0  |        |
| flarum-subscriptions               | v1.4.0  |        |
| askvortsov-rich-text               | v2.1.7  |        |
| fof-discussion-language            | 1.2.7   |        |
| v17development-seo                 | v1.8.0  |        |
| flarum-sticky                      | v1.4.0  |        |
| flarum-lock                        | v1.4.0  |        |
| flarum-emoji                       | v1.4.0  |        |
| flarum-likes                       | v1.4.0  |        |
| afrux-forum-widgets-core           | v0.1.7  |        |
| flarum-suspend                     | v1.4.0  |        |
| flarum-approval                    | v1.4.0  |        |
| fof-oauth                          | 1.2.2   |        |
| fof-impersonate                    | 1.1.0   |        |
| fof-follow-tags                    | 1.1.6   |        |
| zerosonesfun-member                | 1.2     |        |
| zerosonesfun-direct-links          | 3.1     |        |
| zerosonesfun-bbcode-advanced-image | 0.3     |        |
| v17development-user-badges         | v1.1.0  |        |
| v17development-blog                | v0.5.0  |        |
| therealsujitk-gifs                 | v4.1.1  |        |
| the-turk-stickiest                 | 2.0.3   |        |
| the-turk-quiet-edits               | 0.1.3   |        |
| the-turk-flamoji                   | 1.0.4   |        |
| sycho-profile-cover                | v1.3.3  |        |
| sycho-move-posts                   | v0.1.7  |        |
| nearata-twofactor                  | v2.1.0  |        |
| nearata-no-self-likes              | v1.2.1  |        |
| nearata-copy-code-to-clipboard     | v2.1.0  |        |
| michaelbelgium-discussion-views    | v7.1.3  |        |
| justoverclock-welcomebox           | 1.3.7   |        |
| justoverclock-last-users-posts     | 0.3.0   |        |
| justoverclock-custom-html-widget   | 0.1.4   |        |
| ianm-synopsis                      | 1.2.1   |        |
| ianm-syndication                   | 1.2.2   |        |
| ianm-html-head                     | 1.1.0   |        |
| glowingblue-password-strength      | 3.1.0   |        |
| fof-webhooks                       | 1.1.0   |        |
| fof-user-directory                 | 1.2.3   |        |
| fof-user-bio                       | 1.1.0   |        |
| fof-upload                         | 1.2.3   |        |
| fof-terms                          | 1.2.0   |        |
| fof-subscribed                     | 1.1.2   |        |
| fof-socialprofile                  | 1.1.4   |        |
| fof-sitemap                        | 1.0.3   |        |
| fof-share-social                   | 1.1.0   |        |
| fof-recaptcha                      | 1.1.0   |        |
| fof-reactions                      | 1.1.2   |        |
| fof-polls                          | 1.1.0   |        |
| fof-pages                          | 1.0.4   |        |
| fof-nightmode                      | 1.4.1   |        |
| fof-moderator-notes                | 1.1.0   |        |
| fof-links                          | 1.1.2   |        |
| fof-linguist                       | 1.0.4   |        |
| fof-ignore-users                   | 1.1.0   |        |
| fof-forum-statistics-widget        | 1.0.2   |        |
| fof-formatting                     | 1.0.2   |        |
| fof-filter                         | 1.1.1   |        |
| fof-drafts                         | 1.1.2   |        |
| fof-disposable-emails              | 1.0.0   |        |
| fof-default-group                  | 1.1.0   |        |
| fof-best-answer                    | 1.2.3   |        |
| fof-bbcode-details                 | 1.1.0   |        |
| fof-analytics                      | 1.1.0   |        |
| flarumtr-mobile-search             | v1.2    |        |
| flarum-statistics                  | v1.4.1  |        |
| flarum-pusher                      | v1.4.0  |        |
| flarum-nicknames                   | v1.4.0  |        |
| flarum-mentions                    | v1.4.0  |        |
| flarum-lang-turkish                | 1.2.0.2 |        |
| flarum-lang-english                | v1.4.0  |        |
| flarum-bbcode                      | v1.4.0  |        |
| dem13n-topic-starter-label         | 0.1.8   |        |
| dem13n-discussion-cards            | 0.3.8   |        |
| davwheat-custom-sidenav-links      | 1.0.1   |        |
| davwheat-ads                       | 1.2.0   |        |
| datlechin-posted-on                | v0.1.6  |        |
| datlechin-birthdays                | v1.2.4  |        |
| darkle-fancybox                    | 1.1.2   |        |
| clarkwinkelmann-username-blacklist | 1.0.0   |        |
| clarkwinkelmann-passwordless       | 1.4.0   |        |
| clarkwinkelmann-likes-received     | 1.0.2   |        |
| clarkwinkelmann-group-list         | 1.0.0   |        |
| clarkwinkelmann-group-invitation   | 1.0.1   |        |
| clarkwinkelmann-create-user-modal  | 1.3.1   |        |
| clarkwinkelmann-circle-groups      | 1.0.1   |        |
| clarkwinkelmann-bookmarks          | 1.1.0   |        |
| clarkwinkelmann-author-change      | 1.0.2   |        |
| blomstra-notification-deleter      | 0.2.1   |        |
| blomstra-no-email-notifications    | 0.1.0   |        |
| askvortsov-pwa                     | v3.1.3  |        |
| askvortsov-moderator-warnings      | v0.6.1  |        |
| askvortsov-markdown-tables         | v1.2.1  |        |
| askvortsov-checklist               | v1.3.1  |        |
| antoinefr-bbcode-fa                | v1.0.0  |        |
| afrux-online-users-widget          | v0.1.6  |        |
| afrux-news-widget                  | v0.1.1  |        |
| acpl-my-tags                       | 1.2.0   |        |
| acpl-mobile-tab                    | 1.1.0   |        |
+------------------------------------+---------+--------+
Base URL: https://www.teteos.net`

**Comment by hasanmerkit** [comment]
Hey! My extension version is still keep 0.5.0 version but whyy :/
"composer update v17development/flarum-blog" output:

```
Loading composer repositories with package information
Updating dependencies
Info from https://repo.packagist.org: #StandWithUkraine
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
155 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
