### ISSUE TITLE
Revert change to hide comments when there are no comments

### ISSUE THREAD

**Issue by iamdarkle** [v17development/flarum-blog#121]
In the last update this was added, for when comments are disabled or there are no comments, I think it's a great idea when comments are disabled, but I think it makes no sense to hide comments when there are no comments, as all new posts have no comments, so the comment box doesn't appear on any post, making it impossible for anyone to comment on them.

**Comment by hrvoje-hr** [comment]
+1

After the update, there is no commenting box anymore under articles with zero comments. Really missing.
