### ISSUE TITLE
Blog posts and discussions are not separate

### ISSUE THREAD

**Issue by hanzalajamal31** [v17development/flarum-blog#130]
Thank for this wonderful extension.
I installed this extension but have an issue.

When I create a discussion, it shows in the homepage also in the /blog page.

When I create a blog post, it shows in the homepage with discussions and also /blog page.

I want to make this separate. Discussion should be only on homepage, and blog posts should only be on /blog page.

I also enabled the option to hide blog posts on discussions, but unable to hide discussions on /blog page.

Please fix this.

Thanks

**Comment by ctml91** [comment]
You need to select specific blog categories/tags, there is an option in the settings.

Blog posts must use this tag (or one of them) and then will only be shown on blog page.

**Comment by hanzalajamal31** [comment]
@ctml91 Thanks
The issue is solved, but one more question.
If I choose some tags only for blog, and only admin and mod can write blog posts.
So how can I hide those blog categories from the discussion editor for other users.
Thanks
