### ISSUE TITLE
Hide blog tags from other users

### ISSUE THREAD

**Issue by hanzalajamal31** [v17development/flarum-blog#131]
Hey @jaspervriends @askvortsov1 @flarum-bot @Ralkage @davwheat @iPurpl3x @imorland @luceos !

If I choose some tags only for blog, and only admin and mod are permitted to write blog posts.
So how can I hide those blog categories from the discussion editor for other users.
Thanks

**Comment by askvortsov1** [comment]
If you restrict who can view and start discussions in these tags from the permissions page, that should hide them from regular users.
