### ISSUE TITLE
You do not have permission to do that at detail page when not log in

### ISSUE THREAD

**Issue by nvhug001** [v17development/flarum-blog#136]
go https://domain.xxx/blog/37-test Ex: [link](https://ceramichacker.com/blog/14-8x-design-patterns-conventions-and-testing)
I saw **You do not have permission to do that.**
Please help to fix issues, Thank you.
I already check log and saw:
401 Unauthorized
POST https://zed.mee/api/discussions/37

`Flarum\User\Exception\NotAuthenticate 401 Unauthorized
POST https://zed.mee/api/discussions/37

Flarum\User\Exception\NotAuthenticatedException in C:\xampp\htdocs\zed\vendor\flarum\core\src\User\User.php:632
Stack trace:
#0 C:\xampp\htdocs\zed\vendor\flarum\core\src\Discussion\Command\ReadDiscussionHandler.php(45): Flarum\User\User->assertRegistered()
#1 C:\xampp\htdocs\zed\vendor\illuminate\bus\Dispatcher.php(122): Flarum\Discussion\Command\ReadDiscussionHandler->handle(Object(Flarum\Discussion\Command\ReadDiscussion))
#2 C:\xampp\htdocs\zed\vendor\illuminate\pipeline\Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Discussion\Command\ReadDiscussion))
#3 C:\xampp\htdocs\zed\vendor\illuminate\pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Discussion\Command\ReadDiscussion))
#4 C:\xampp\htdocs\zed\vendor\illuminate\bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))dException in C:\xampp\htdocs\zed\vendor\flarum\core\src\User\User.php:632
Stack trace:
#0 C:\xampp\htdocs\zed\vendor\flarum\core\src\Discussion\Command\ReadDiscussionHandler.php(45): Flarum\User\User->assertRegistered()
#1 C:\xampp\htdocs\zed\vendor\illuminate\bus\Dispatcher.php(122): Flarum\Discussion\Command\ReadDiscussionHandler->handle(Object(Flarum\Discussion\Command\ReadDiscussion))
#2 C:\xampp\htdocs\zed\vendor\illuminate\pipeline\Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Discussion\Command\ReadDiscussion))
#3 C:\xampp\htdocs\zed\vendor\illuminate\pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Discussion\Command\ReadDiscussion))
#4 C:\xampp\htdocs\zed\vendor\illuminate\bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))`

**Comment by jaspervriends** [comment]
Fixed with #138
