### ISSUE TITLE
No header or hero on "blog" page slug

### ISSUE THREAD

**Issue by phenomlab** [v17development/flarum-blog#14]
Having the ability to include the hero section on the blog page would be great. It looks odd when discussions are loaded that have a header, and the blog page doesn't.

**Comment by ctml91** [comment]
I'd ask this be optional, in my case the welcome hero would look out of place here and takes up too much space.

**Comment by phenomlab** [comment]
> I'd ask this be optional, in my case the welcome hero would look out of place here and takes up too much space. 

Yes, I agree with that. In my case is makes sense, but not for everyone of course 😁

**Comment by phenomlab** [comment]
Curious to know if there is any update to this ? Raised in November 2020, but sadly no movement. I'd also like to know if it's possible to add the hero header using the root extend.php but targeting the blog extension ?

**Comment by pboschma** [comment]
Thank you for writing. We're currently busy with some personal stuff and other products. We didn't forget and we'll work on an update soon.
