### ISSUE TITLE
Latest version ( v0.6.1) does not load content or admin controls on direct navigation to hidden articles

### ISSUE THREAD

**Issue by eddiewebb** [v17development/flarum-blog#142]
I have just updated to  v0.6.1 and it prompty broke my blog pages.

### Expected behavior:
- admin sees content
- admin sees article settings to change visibility, title, image, 

### Actual behavior:
- admin sees light gray loading bars, no content
- hard refresh does not change it
- direct navigation does not hcnage it

Going to blog homepage then article loads it, but without the 'article settings' button.

### Steps to recreate:
1. visit any active blog page
2. from article settings, choose 'hide article'
3. Only gray content will show. 
4. Settings menu disapears

### Workaeround
1. disable blog extension
2. restore article (now a discussion)
3. Reenable blog extension

<img width="1281" alt="Screen Shot 2022-06-18 at 7 24 33 AM" src="https://user-images.githubusercontent.com/5262154/174435651-c310fcb0-b460-4c1b-8344-eb437e5ae000.png">

<img width="1217" alt="Screen Shot 2022-06-18 at 7 31 27 AM" src="https://user-images.githubusercontent.com/5262154/174435652-4cdf32e3-d262-401a-bb09-41b6e33c1f16.png">

**Comment by jaspervriends** [comment]
Thanks for reporting! Issue has been fixed in next release :)
