### ISSUE TITLE
removed tags dont update in blog extension 

### ISSUE THREAD

**Issue by MissGamerz** [v17development/flarum-blog#143]
if you delete tags without removing them from the blog categories you end up with ghost categories in the extension 
![image](https://user-images.githubusercontent.com/32730401/175789549-7a86571a-b512-4a6b-b747-2cc83f6733e5.png)
![image](https://user-images.githubusercontent.com/32730401/175789571-c3b1bd4b-f8f8-46a0-b52f-4281fbe1c55b.png)

i only have 3 here it says i have 6

where do i clear this information to fix this

**Comment by jaspervriends** [comment]
Thanks for reporting! Fixed in new version :)

**Comment by MissGamerz** [comment]
ty
