### ISSUE TITLE
Installation via composer, requirements could not be resolved

### ISSUE THREAD

**Issue by moturiphil** [v17development/flarum-blog#153]
Your requirements could not be resolved to an installable set of packages.

This is on Laravel 9, PHP8.0

  Problem 1
    - flarum/core dev-master requires league/flysystem ^1.0.11 -> found league/flysystem[1.0.11, ..., 1.x-dev] but the package is fixed to 3.10.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - flarum/core[v1.1.0, ..., 1.x-dev] require illuminate/bus ^8.0 -> found illuminate/bus[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - v17development/flarum-blog[v0.6.4, ..., 0.6.x-dev] require flarum/core ^1.2.0 -> satisfiable by flarum/core[v1.2.0, ..., 1.x-dev].
    - flarum/core 1.x-dev is an alias of flarum/core dev-master and thus requires it to be installed too.
    - Root composer.json requires v17development/flarum-blog ^0.6.4 -> satisfiable by v17development/flarum-blog[v0.6.4, 0.6.x-dev].

**Comment by davwheat** [comment]
I assume you mean Laravel 8, since Flarum doesn't use Laravel 9 yet.

What version of Flarum are you running?
