### ISSUE TITLE
Error while trying to visit the blog with a clean browser

### ISSUE THREAD

**Issue by therealmaxmoon** [v17development/flarum-blog#159]
I was testing Flarum on FreeFlarum, but had [issues](https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/4496) running the Blog extension.

The blog isn't accessible from outside. Every time I use [a link to a blog post](https://utopifytest.freeflarum.com/blog/3-my-first-blogpost) (in a fresh browser), it only shows the following error:

`An error occurred while trying to load this page.`

Is this a known issue of the extension or is it possible that it's a problem of FreeFlarum?

### Versions

Flarum: 1.8.1
PHP: 8.2.4
MySQL: 10.11.2-MariaDB-1:10.11.2+maria~ubu2204-log
Blog extension: v0.7.2

**Comment by davwheat** [comment]
Try enabling v17 SEO.

**Comment by davwheat** [comment]
The technical reasons are in #150 

Essentially, the PHP code will see SEO if SEO is installed but not enabled (like on FreeFlarum). This means that Blog will attempt to use SEO features which then won't work because SEO isn't actually enabled as an extension.

**Comment by therealmaxmoon** [comment]
Please don't close this issue, because it is still an issue.

If the blog extension only checks if SEO is installed, but not if it's active, it's a huge problem. Why can't it be fixed, so it will work like other extensions, which have dependencies to other extensions and give proper error messages so that the user knows what to do? And extensions can't be activated until the dependencies are active.

If solving the dependency issue is too much, please consider to add a warning in the first lines on the admin page of blog with a small warning that SEO MUST be active otherwise the blog will not work.

**Comment by davwheat** [comment]
I closed it because it's a duplicate of an existing issue I mentioned above. Having two issues detailing the same issue is useless from a developer perspective.

**Comment by therealmaxmoon** [comment]
Ah, I see.

Thank you :)
