### ISSUE TITLE
Back Button Header Navigation redirects to blog

### ISSUE THREAD

**Issue by ctrought** [v17development/flarum-blog#20]
If I click on a blog post that is visible from the discussions page, I cannot use the flarum back button in the header navigation, I guess because of the redirect used to take you to the blog it will just redirect you back to the blog again. The only way to get back to the discussion page I could find was to use a header link (site logo), which may not be obvious for normal users.

Discussion Post: https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/28

**Comment by ctml91** [comment]
Note: this is only seen with the redirect features on, as the back button goes to either the tag or discussion depending on the combination you use and which even (tag or discussion) caused your initial redirect.
