### ISSUE TITLE
Primary blog tags removed from tags list/page

### ISSUE THREAD

**Issue by ctml91** [v17development/flarum-blog#21]
If I select a primary tag for the blog tag, it gets removed from the tag list on the sidebar, and the tag page, so the only way I could figure out how to get to the blog page was to find a discussion matching the blog tags. I am not sure if that is intentional, because a secondary tag could be beneath a non blog primary tag, but a primary tag consists of only blog posts, however it is a little confusing to navigate as a result.

A shortcut to the blog overview, or perhaps optionally leave the tags in the tag list (perhaps some unique way to display them with other tags) to keep them discoverable would be nice. 

Discussion Post: https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/28

**Comment by jaspervriends** [comment]
You are able to turn off that behaviour by turning off "Hide tags in taglist" :)

![image](https://user-images.githubusercontent.com/4417659/99595563-3eaa3300-29f5-11eb-9dbc-a991028dcf24.png)

**Comment by ctml91** [comment]
You win there :) Sorry, I missed that. 

I guess one question is the behaviour for the tags page then. The primary tag is not visible from there, but blog categories using secondary tags do still show.

The other thing, I guess as an enhancement would be a shortcut to the blog overview, maybe in the list on discussion list page.. thoughts? Basically the goal is to highlight blogs, as the normal tag list are not indicative they are special posts.

![image](https://user-images.githubusercontent.com/74685281/99597123-84e79e00-29c5-11eb-9e43-240d25917dc4.png)

**Comment by jaspervriends** [comment]
> I guess one question is the behaviour for the tags page then. The primary tag is not visible from there, but blog categories using secondary tags do still show.
Did you clear the cache and refresh? Then the tag should also be visible on the tag page.

> The other thing, I guess as an enhancement would be a shortcut to the blog overview, maybe in the list on discussion list page.. thoughts? Basically the goal is to highlight blogs, as the normal tag list are not indicative they are special posts.

That's something I was thinking about too! I'll make sure to add it :)

**Comment by ctml91** [comment]
> Did you clear the cache and refresh? Then the tag should also be visible on the tag page.

Yes I signed on in incognito, but I am referring to the behaviour when the hidden option is selected. From the tags page, the primary tag will be hidden, but secondary tag are not hidden and still shown at the bottom of the tag page. I don't plan to use the hiding behaviour anyways but just wanted to mention it anyway because I assume it is not expected. Thanks!

**Comment by askvortsov1** [comment]
This should be fixed in #41
