### ISSUE TITLE
Missing pagination button

### ISSUE THREAD

**Issue by jaspervriends** [v17development/flarum-blog#33]
After more than 30 articles, there's no pagination button to load more.

**Comment by hrvoje-hr** [comment]
@jaspervriends on my test Flarum with beta13/Blog v0.1.6 there is no issue with pagination.

You can check it here:
http://phpstack-394430-1689724.cloudwaysapps.com/aplikacija/public/

**Comment by jaspervriends** [comment]
Woops good one! I actually fixed it in v0.1.6 a few hours ago, but forgot to close this issue! Thanks for testing it out though!
