### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KitsuneSolar** [v17development/flarum-blog#40]
Hello! 
I did [localization](/marketplace-flarum/flarum-l10n-ext-russian/blob/main/locale/v17development-flarum-blog.yml). But it doesn't work. What could be problem?

**Comment by jaspervriends** [comment]
Hi! Are you still experiencing issues? I do see the text shows English text, did you translate it already in your language-extension?

**Comment by KitsuneSolar** [comment]
I am updating localizations. No translation yet.

**Comment by jaspervriends** [comment]
When looking at the commit history I see you reverted some translations: https://github.com/marketplace-flarum/flarum-l10n-ext-russian/commits/main/locale/v17development-flarum-blog.yml

Seems like https://github.com/marketplace-flarum/flarum-l10n-ext-russian/commit/36f3f0211799e8fcbd271c21fd5006c833ad298c#diff-f65b2b867a9ae454e2c4c97e43e245f219125ad762f72422f77b4a46efe211a9 contains your translations
