### ISSUE TITLE
Flarum Blog as homepage

### ISSUE THREAD

**Issue by T0MMYRR** [v17development/flarum-blog#43]
This extension is incredible and undoubtedly deserves to be the homepage of many websites that use flarum, in the "basics" section it doesn't give the option to put the blog extension as the homepage as it does with FoF Pages for example.

I'm not sure if extension developers can modify this configuration section or if it depends on the official versions of Flarum, but it would be nice to have it or to add the option directly in the blog extension configuration.

**Comment by luceos** [comment]
👍 can be closed
