### ISSUE TITLE
Incompatibility with FoF Formatting

### ISSUE THREAD

**Issue by IamDarkle** [v17development/flarum-blog#44]
Autoimage, Autovideo and MediaEmbed do not work, although for images there is no problem as they can still be attached and it is for convenience, in the case of videos I think it is a problem as as far as I know no other way to attach videos.

**Comment by pboschma** [comment]
We'll take a look to see what needs to be done to make it compatible. Thanks for reporting!

**Comment by jaspervriends** [comment]
Hi! I'm currently checking this issue, but I cannot reproduce the issue. Are you still experiencing this?

**Comment by IamDarkle** [comment]
No, it was a bit weird, because for weeks it didn't work for me, in my case as I had to change server provider and reinstall everything, it started working without problem. I don't think anyone has experienced this again so I close the issue.
