### ISSUE TITLE
Bio text leaks out.

### ISSUE THREAD

**Issue by mikejones3** [v17development/flarum-blog#47]
I have a link in my bio and it leaks out of the bio on blog posts. Image attached
<img width="454" alt="Screen Shot 2021-01-19 at 4 58 33 PM" src="https://user-images.githubusercontent.com/13171497/105195367-6dc14b80-5aef-11eb-9d42-2673a187e4c0.png">

**Comment by therealmaxmoon** [comment]
I wanted to recommend using markdown to make a word clickable, but currently [markdown doesn't work with the blog (profile)](https://github.com/v17development/flarum-blog/issues/160).
