### ISSUE TITLE
Implement FoF Upload

### ISSUE THREAD

**Issue by jaspervriends** [v17development/flarum-blog#5]
It will be great to have FoF Upload implemented to set images.

**Comment by ctml91** [comment]
@jaspervriends , is this for the Blog image, or for images in the post? I am on v0.2.1 but don't see any option to upload images to the blog image settings. The upload form is only available for the post content, let me know.. I might be confused lol.

**Comment by jaspervriends** [comment]
> @jaspervriends , is this for the Blog image, or for images in the post? I am on v0.2.1 but don't see any option to upload images to the blog image settings. The upload form is only available for the post content, let me know.. I might be confused lol.

It's for the blog featured image. I've worked on a media manager for the FoF Upload extension which we could use for this. After this PR has been merged I'll update the Blog extension to support custom uploads :)

**Comment by ctml91** [comment]
Ok thanks :) so if the above has been merged already (for the featured image upload) how does this work, because I am not seeing the option on my end... onlhttps://github.com/v17development/flarum-blog/pull/29 

![image](https://user-images.githubusercontent.com/74685281/106816818-f12c8200-6643-11eb-81c7-ee2841cf9c5b.png)

**Comment by jaspervriends** [comment]
> Ok thanks :) so if the above has been merged already (for the featured image upload) how does this work, because I am not seeing the option on my end..  https://github.com/v17development/flarum-blog/pull/29 

Hi! Sorry, forgot to add the link to the PR: The PR is still open: https://github.com/FriendsOfFlarum/upload/pull/262

So it isn't implemented yet. But after that it will be updated

**Comment by ctml91** [comment]
Oh wow.. that looks.... **amazing**. You guys absolutely kill it with your extensions.

And the feature imaged will be able to hook into that? :)

**Comment by jaspervriends** [comment]
> Oh wow.. that looks.... **amazing**. You guys absolutely kill it with your extensions.
> 
> And the feature imaged will be able to hook into that? :) 

Yup that is the idea :)

**Comment by IamDarkle** [comment]
I know this is in the plans and will be done later, but I was wondering if it would be possible that the images when uploaded can be entered in a folder, currently I do it manually in my S3 storage, I do the following structure /blog/189/hey.png

The number 189 for example I take it from the post itself:
![Captura de pantalla 2021-05-30 005017](https://user-images.githubusercontent.com/15818451/120086812-6c79de00-c0e2-11eb-89a0-72441e593ded.png)

Would it be possible to automatically upload the images through the Blog extension with this folder structure? Or would this be a FOF Upload problem?

**Comment by ayyilmaz** [comment]
I think this feature is temporary solution: https://github.com/v17development/flarum-blog/issues/78
