### ISSUE TITLE
Post titles need more distinction 

### ISSUE THREAD

**Issue by mikejones3** [v17development/flarum-blog#50]
The post title looks no different then heading text in a post. If you have a heading as your first text in a post the post title matches it and it just looks odd. 

<img width="781" alt="Screen Shot 2021-01-19 at 6 39 26 PM" src="https://user-images.githubusercontent.com/13171497/105196070-18d20500-5af0-11eb-84dc-3e03aa3170d9.png">

**Comment by jaspervriends** [comment]
Fixed in next release, thanks for reporting 😎
