### ISSUE TITLE
Switch to hide posts

### ISSUE THREAD

**Issue by IamDarkle** [v17development/flarum-blog#59]
I would like to have the possibility of having a switch like the one that allows us to make a highlighted post, that allows us to hide a post, so that the only way to see that post is via url.

**Comment by jaspervriends** [comment]
Hi! Is this meant for moderation/review purposes? Otherwise you could use the `blog review` feature

**Comment by T0MMYRR** [comment]
> Hi! Is this meant for moderation/review purposes? Otherwise you could use the `blog review` feature

Hi! actually what I had in mind was to hide posts from the blog's recent list, so that they can only be accessed via url.

**Comment by hrvoje-hr** [comment]
For now you can create private forum tag and put the article there. It's the same result, maybe even better.

**Comment by T0MMYRR** [comment]
Oh, it hadn't really crossed my mind, I'll definitely give it a whirl. The problem I see is that for example all users who have X permissions would be able to access which is fine, but they would also get all these random out of context posts in the blog's recent list, which wouldn't be ideal... I'll have a look at it as I haven't gone too deep into tag permissions.

**Comment by hrvoje-hr** [comment]
You can chose to hide discussions from that tag in all discussions list. Also, you can set that tag permissions only to admin.

**Comment by jaspervriends** [comment]
Is this an issue that should stay open or can we close this as we can use the tag permissions?

**Comment by IamDarkle** [comment]
Sorry, I completely forgot about this problem, currently using @hrvoje-hr solution 👍
