### ISSUE TITLE
add isBlog attribute to tag

### ISSUE THREAD

**Issue by andreystavitsky** [v17development/flarum-blog#60]
I think it's a good idea to have an "isBlog" attribute in tag attributes

**Comment by jaspervriends** [comment]
Of course this is possible. Is there any specific reason why you would like to have this attribute added to the tags?

**Comment by andreystavitsky** [comment]
> Of course this is possible. Is there any specific reason why you would like to have this attribute added to the tags?

Currently I'm working on Flutter mobile application that will use Flarum REST API to implement Blog reader, so I need ability to select tags that belong to Blog section of Flarum. I know that there is "blogTags" attribute, but it require extra API call to get that data when you getting tags related to Blog section to implement category filter. Instead of that API call I can just grab all the tags and then filter them in my app by this attribute.

Obviously I can be wrong and there can be easier way to get Blog-related tags only without adding extra attributes and without extra API calls, but I can't find how to do this

**Comment by jaspervriends** [comment]
Thanks for the feedback. We've added it in the upcoming version! 🎉
