### ISSUE TITLE
Blog as home page shows every post as a blog post

### ISSUE THREAD

**Issue by ctml91** [v17development/flarum-blog#61]
When you set the blog to be your homepage every forum post will show as a blog post, no filtering is applied :) :(

**Comment by jaspervriends** [comment]
That's interesting, looking at the controller there shouldn't be anything else then blog posts on this page ( https://github.com/v17development/flarum-blog/blob/master/src/Controller/BlogOverviewController.php#L40 ).

Do you have an example webpage which I could check? Locally I cannot reproduce this issue

**Comment by hrvoje-hr** [comment]
I too can't replicate the issue.

**Comment by ctml91** [comment]
This behaviour is caused by a bug in this extension, workaround is to enable the SSO extension last to avoid impacting routes created by extension **after** SSO is enabled https://discuss.flarum.org/d/21666-php-and-wordpress-single-sign-on-sso-with-optional-jwt-addon/395

Closing
