### ISSUE TITLE
Notify blog article creator of new replies

### ISSUE THREAD

**Issue by phenomlab** [v17development/flarum-blog#70]
Currently, when someone responds to a blog post article without using mention, there is no notification. This means I missed a response to a blog article by three days :-(

**Comment by ctml91** [comment]
I think this is still compatible with subscriptions, but hidden at blog level in the UI. You could try either

- use the extension that subscribes you to threads you post in by default 
- in your forum, under your blog tag (while redirects are disabled for tags so you remain on flarum discussion list page) , lurk the blog tag(s) 
- install Clark's follow tags prompt, and set the blog tags to lurking
