### ISSUE TITLE
Accessing link directly results in JS error 

### ISSUE THREAD

**Issue by phenomlab** [v17development/flarum-blog#71]
When accessing a link directly from an external resource, the spinning logo appears continuously, and the below error is recorded in the console

```
Uncaught TypeError: t.title is not a function
    at e.a.show (BlogItem.js:59)
```

**Comment by jaspervriends** [comment]
Are you still experiencing this issue? When I'm looking at the code, this should only be called when the article is found and rendering. Is there still an example available on your forum?

**Comment by jaspervriends** [comment]
I'll close this issue due to inactivity. If you are still experiencing this issue let me know!
