### ISSUE TITLE
Feature Request:  option to show first image of article as featured image

### ISSUE THREAD

**Issue by ayyilmaz** [v17development/flarum-blog#78]
In the current situation, the blog plugin moves all the content in the category to the blog section, so a lot of content appears. We will need to upload featured images one by one for each content. Instead, if the featured image of the article is not selected, it will automatically select the first image of a post that has already been added.

**Comment by jaspervriends** [comment]
I think this issue can be closed, it's now possible to select uploaded images as featured image :)

If you disagree you can re-open this issue.
