### ISSUE TITLE
Allow direct of upload/media manager for article image url

### ISSUE THREAD

**Issue by ctml91** [v17development/flarum-blog#86]
Allow direct upload or choose existing image for media manager.

![image](https://user-images.githubusercontent.com/74685281/115765184-70447300-a374-11eb-9ed2-1f0f659c4b3c.png)

**Comment by jaspervriends** [comment]
Hey! We already have an issue about this feature: https://github.com/v17development/flarum-blog/issues/5

Hope we can implement this soon though :)

I'll close this issue for now
