### ISSUE TITLE
Blog article Composer

### ISSUE THREAD

**Issue by iPurpl3x** [v17development/flarum-blog#9]
It would be nice to have a dedicated composer for blog articles. Where you can directly define things like summary and teaser image. (also maybe use the naming "teaser image" in the UI?...)

**Comment by mapleleafs89** [comment]
I would love to be able to define the blog attributes such as the image during the creation. Currently there is a period where the blog post is missing attributes like image, etc until it is retroactively added. As for image naming, I think "Blog image" or something like that works just fine.

**Comment by jaspervriends** [comment]
Implemented in v0.1.7
