### ISSUE TITLE
Tags page breaks in Flarum V1

### ISSUE THREAD

**Issue by flarumtr** [v17development/flarum-blog#91]
Blog extension compatible with Flarum V1 release causes tags page to break.

**Comment by jgupta** [comment]
Error at our end.

`mount-redraw.js:15 TypeError: Cannot read property 'children' of undefined
    at e.<anonymous> (extendTagOverview.js:13)
    at e.forEach.t.<computed> [as view] (extend.js:35)
    at Function.a (render.js:30)
    at render.js:155
    at render.js:160
    at l (render.js:66)
    at u (render.js:50)
    at h (render.js:374)
    at render.js:444
    at f (render.js:415)`

**Comment by uamv** [comment]
I'm encountering a similar issue at [wire.gravityhopper.com](https://wire.gravityhopper.com). If I load the [tag page](https://wire.gravityhopper.com/tags) directly, it loads fine. However, when going to the tag page from some other page on the forum, I encounter errors _(I don't think precisely the same as that indicated above)_.

**Comment by uamv** [comment]
FYI, current workaround is to uncheck setting at **Blog → Categories → Hide tags in taglist** .

**Comment by ihhddis** [comment]
> FYI, current workaround is to uncheck setting at **Blog → Categories → Hide tags in taglist** .

Should the setting be maintained as is? Or when re-activating it, it does not happen anymore?

**Comment by uamv** [comment]
I think at this point that the setting needs to remain unchecked in order to avoid this issue.

**Comment by iPurpl3x** [comment]
@jaspervriends or @pboschma, could you fix this asap ? It's quite an annoying bug. Also I think you already know how to fix it since the same issue was also in the premium flarum-support extension.

**Comment by luceos** [comment]
I am looking at this right now.
