### ISSUE TITLE
Issue with Rich Text Editor extension

### ISSUE THREAD

**Issue by jaspervriends** [v17development/flarum-blog#92]
> Im go try without Rich text and i gonna tell you if this fix my problem.
> I tried and that fix my problem. Thx! Now i know Rich Text have problem with blogs.
> https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/318

Extension: https://discuss.flarum.org/d/26455-wysiwyg-rich-text-editor

**Comment by shawny43** [comment]
The problem is still on. I still waiting for awnsers soo im keeping patient.
