### ISSUE TITLE
Error backtracking from a post with FoF Discussion Language

### ISSUE THREAD

**Issue by iamdarkle** [v17development/flarum-blog#94]
After a lot of testing I have discovered that the culprit of this error is the FoF Discussion Language extension. 

As you can see in the gif when you go back after clicking on a post you get an error that forces you to reload the page completely.

![qIRbl2WJKv](https://user-images.githubusercontent.com/15818451/123725791-07efa180-d88f-11eb-83db-27ddf0cd76b0.gif)

**Edit:**

After further investigation I think I know exactly what happens with FoF Discussion Language, the way to reproduce the bug is very simple just install FoF Discussion Language and the Blog extension (set as home page).

When you set 2 languages in FoF Discussion Language e.g. English and French, select the language in some blog entries and you are ready to reproduce the bug.

I think what happens is this:

![Inkedmsedge_rDo6ewRf4J_LI](https://user-images.githubusercontent.com/15818451/124539014-f7a26e00-de1c-11eb-973c-dff4bda3fbc8.jpg)

As you can see in the image for some reason there is no language selected, this did not happen in previous versions, this causes that when you go back from a post nothing is shown, because all blog posts have some language assigned to them

**Comment by pboschma** [comment]
Well.. That's a strange issue. Thank you for reporting.

**Comment by ihhddis** [comment]
Is there any eta for this? I am having the same problem

**Comment by iamdarkle** [comment]
As far as I have been able to test it has been solved with https://github.com/v17development/flarum-blog/pull/99 it's running smoothly, I close the issue.
